// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file esrgan_lite_op7_rs6_nchw.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace WinML_SuperRes_Demo
{
    
    public sealed class esrgan_lite_op7_rs6_nchwInput
    {
        public ImageFeatureValue input_0; // shape(1,3,50,50)
    }
    
    public sealed class esrgan_lite_op7_rs6_nchwOutput
    {
        public ImageFeatureValue Identity; // shape(1,3,200,200)
    }
    
    public sealed class esrgan_lite_op7_rs6_nchwModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<esrgan_lite_op7_rs6_nchwModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            esrgan_lite_op7_rs6_nchwModel learningModel = new esrgan_lite_op7_rs6_nchwModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<esrgan_lite_op7_rs6_nchwOutput> EvaluateAsync(esrgan_lite_op7_rs6_nchwInput input)
        {
            binding.Bind("input_0", input.input_0);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new esrgan_lite_op7_rs6_nchwOutput();
            output.Identity = result.Outputs["Identity"] as ImageFeatureValue;
            return output;
        }
    }
}

